app:
 name: "web_app"
 mode: "dev"
 port: 8081
 version: "V0.01"

log:
 level: "debug"
 file_name: "web_app.log"
 max_size: 200
 max_age: 30
 max_backup: 7

mysql:
 host: "127.0.0.1"
 port: 3306
 user: "wangfei"
 password: "titan721"
 db_name: "myspace"
 max_open_conn: 200
 max_id_conn: 50

redis:
 host: "127.0.0.1"
 port: 6379
 db: 0
 password: ""
 pool_size: 100
